#!/usr/bin/env node
/**
 * Coverage matrix: turns the target columns for this title into a measurable list, and writes
 * reports/coverage-report.md. It exists so "how much of the game does this site actually cover" is a
 * number rather than an impression.
 *
 * A column is satisfied only by published entries that are either in one of the column's categories or
 * named explicitly. Content that cannot yet be grounded stays in content/draft and is counted, with the
 * reason it is not published, so a gap is visible instead of being quietly filled.
 *
 * Quality is checked at the same time: duplicate titles, duplicate summaries, placeholder text and
 * summaries under the minimum length all fail, so a column cannot be satisfied with filler.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const MIN_SUMMARY = 80;
const PLACEHOLDER = /\b(tbd|todo|lorem|placeholder|coming soon|to be written)\b/i;
const root = process.cwd();
const cfg = JSON.parse(readFileSync(join(root, 'config', 'coverage.json'), 'utf8'));

const readTier = (tier) => {
  const dir = join(root, 'content', tier);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith('.json'))
    .map((f) => ({ file: f, data: JSON.parse(readFileSync(join(dir, f), 'utf8')) }));
};
const articles = existsSync(join(root, 'content', 'articles'))
  ? readdirSync(join(root, 'content', 'articles')).filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(join(root, 'content', 'articles', f), 'utf8')))
  : [];
const published = readTier('published');
const drafts = readTier('draft');
const reference = readTier('reference');
const byId = new Map(published.map((e) => [e.data.id, e.data]));

// ---- quality ----
const bad = [];
const titles = new Map();
const summaries = new Map();
for (const e of published) {
  const { id, title, summary } = e.data;
  if (!id || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id)) bad.push(id + ': slug is not a clean identifier');
  if (!title || title.length < 8) bad.push(id + ': title missing or short');
  if (!summary || summary.length < MIN_SUMMARY) bad.push(id + ': summary under ' + MIN_SUMMARY + ' characters');
  if (summary && PLACEHOLDER.test(summary)) bad.push(id + ': summary contains placeholder text');
  for (const p of e.data.body ?? []) if (PLACEHOLDER.test(p)) bad.push(id + ': body contains placeholder text');
  if (title) titles.set(title, (titles.get(title) ?? 0) + 1);
  if (summary) summaries.set(summary, (summaries.get(summary) ?? 0) + 1);
}
for (const [t, n] of titles) if (n > 1) bad.push('duplicate title: ' + t);
for (const [s, n] of summaries) if (n > 1) bad.push('duplicate summary: ' + s.slice(0, 60));

// ---- coverage ----
const rows = [];
const gaps = [];
for (const col of cfg.columns) {
  if (col.kind === 'articles') {
    rows.push({ col, pub: articles.length, dra: 0, ref: 0 });
    if (!articles.length) gaps.push('| ' + col.id + ' | ' + col.label + ' | ' + (col.status ?? 'none written') + ' | - |');
    continue;
  }
  const ids = new Set(col.entries ?? []);
  const cats = new Set(col.categories ?? []);
  const pub = published.filter((e) => ids.has(e.data.id) || cats.has(e.data.category));
  const dra = drafts.filter((e) => e.data.column === col.id);
  const ref = reference.filter((e) => e.data.column === col.id);
  rows.push({ col, pub: pub.length, dra: dra.length, ref: ref.length });
  if (pub.length === 0) {
    gaps.push('| ' + col.id + ' | ' + col.label + ' | ' + (col.status ?? 'not yet grounded') + ' | ' +
      (dra.map((d) => d.data.id + (d.data.reason ? ' (' + d.data.reason + ')' : '')).join(', ') || '-') + ' |');
  }
}

writeFileSync(join(root, 'reports', 'coverage-report.md'),
  '# Coverage matrix — ' + cfg.site + '\n\n' +
  'Generated by tools/coverage.mjs from config/coverage.json and the content folders. Every number here is\n' +
  'counted, not claimed: a column counts only published entries, and anything not yet grounded is listed with\n' +
  'the reason it is still a draft.\n\n' +
  '- target columns: ' + cfg.columns.length + '\n' +
  '- columns with at least one published entry: ' + rows.filter((r) => r.pub > 0).length + '\n' +
  '- published entries: ' + published.length + '\n' +
  '- draft entries (not built, not indexed): ' + drafts.length + '\n' +
  '- reference pages (technical, noindex): ' + reference.length + '\n' +
  '- published guides (articles): ' + articles.length + '\n' +
  '- quality failures: ' + bad.length + '\n\n' +
  '| target column | what it covers | published | draft | reference |\n| --- | --- | --- | --- | --- |\n' +
  rows.map((r) => '| ' + r.col.id + ' | ' + r.col.label + ' | ' + r.pub + ' | ' + r.dra + ' | ' + r.ref + ' |').join('\n') +
  '\n\n## Columns with nothing published yet\n\n' +
  (gaps.length ? '| column | target | why it is not published | draft in progress |\n| --- | --- | --- | --- |\n' + gaps.join('\n') +
    '\n\nA column with no published entry is a gap in this site, not a gap in the game: it is either not yet\n' +
  'grounded in the game\'s own files, or written and waiting in content/draft.\n'
    : 'Every target column has at least one published entry.\n') +
  (bad.length ? '\n## Quality failures\n\n' + bad.map((b) => '- ' + b).join('\n') + '\n' : ''),
  'utf8');

console.log('[coverage] ' + cfg.site + ': columns=' + cfg.columns.length +
  ' covered=' + rows.filter((r) => r.pub > 0).length +
  ' published=' + published.length + ' draft=' + drafts.length + ' reference=' + reference.length +
  ' qualityFailures=' + bad.length);
for (const r of rows) if (r.pub === 0) console.log('  GAP  ' + r.col.id + ' (' + r.col.label + ')');
for (const b of bad) console.log('  QUALITY  ' + b);
process.exit(bad.length || gaps.length ? 1 : 0);
