#!/usr/bin/env python3
"""Flag mapped game images that are near-uniform, near-black or near-white before a human looks at them.

The review ledger (reports/image-reviews.md) records the eye check. This script is the cheap first pass: it reads
every record in content/images-manifest.json, opens the exported file, and measures how much of the picture carries
any variation at all. A sheet with almost no variation is either blank, a mask, or a non-colour map that slipped
through the naming check - all of which fail the site's picture rule and must be looked at.

Transparency matters: the pages draw these files on a dark background, so a PNG with an alpha channel is composited
onto that same dark colour before it is measured. Measuring the raw RGBA would report every transparent icon sheet
as a black or white rectangle, which is a false alarm rather than a finding.

Output: reports/image-sanity.md, newest run only, plus a one-line summary on stdout.
"""
import json, os, sys
from PIL import Image, ImageStat

MANIFEST = os.path.join('content', 'images-manifest.json')
REPORT = os.path.join('reports', 'image-sanity.md')

STDDEV_FLOOR = 12.0      # below this a sheet carries almost no variation
UNIFORM_SHARE = 0.90     # share of pixels within +/-6 of the median
DARK_MEDIAN = 24         # median brightness below this is a near-black sheet
LIGHT_MEDIAN = 235       # above this is a near-white sheet
BG = (15, 17, 22)        # the dark page background the site draws pictures on


def measure(path):
    with Image.open(path) as im:
        if im.mode in ('RGBA', 'LA', 'P'):
            rgba = im.convert('RGBA')
            flat = Image.new('RGB', rgba.size, BG)
            flat.paste(rgba, mask=rgba.split()[-1])
            g = flat.convert('L')
        else:
            g = im.convert('L')
        stat = ImageStat.Stat(g)
        mean = stat.mean[0]
        stddev = stat.stddev[0]
        hist = g.histogram()
        total = sum(hist)
        acc = 0
        median = 0
        for value, count in enumerate(hist):
            acc += count
            if acc * 2 >= total:
                median = value
                break
        lo = max(0, median - 6)
        hi = min(255, median + 6)
        uniform = sum(hist[lo:hi + 1]) / float(total)
    return {'mean': mean, 'stddev': stddev, 'median': median, 'uniform': uniform}


def main():
    if not os.path.exists(MANIFEST):
        print('no manifest'); return 1
    records = json.load(open(MANIFEST, encoding='utf-8')).get('records', [])
    rows = []
    for r in records:
        path = os.path.join('content', 'assets', r['file'])
        if not os.path.exists(path):
            rows.append((r, None, 'missing file')); continue
        try:
            rows.append((r, measure(path), ''))
        except Exception as exc:  # noqa: BLE001 - a broken export is a finding, not a crash
            rows.append((r, None, 'unreadable: %s' % exc))

    flagged = []
    for r, m, note in rows:
        if m is None:
            flagged.append((r, m, note)); continue
        reasons = []
        if m['stddev'] < STDDEV_FLOOR:
            reasons.append('almost no variation (stddev %.1f)' % m['stddev'])
        if m['uniform'] > UNIFORM_SHARE:
            reasons.append('%.0f%% of pixels within 6 of the median' % (m['uniform'] * 100))
        if reasons:
            flagged.append((r, m, '; '.join(reasons)))

    lines = ['# Image sanity check', '',
             'Generated by tools/image-sanity.py from content/images-manifest.json and the exported files.',
             'Transparent pictures are composited on the dark page background before measuring, because that is how the',
             'pages draw them. A picture is flagged when it carries almost no variation (stddev below %.0f), when more'
             % STDDEV_FLOOR,
             'than %.0f%% of its pixels sit within 6 of the median, or when the median is near-black (below %d) or'
             % (UNIFORM_SHARE * 100, DARK_MEDIAN),
             'near-white (above %d). A flag is not a verdict: it means the file has to be looked at by eye.' % LIGHT_MEDIAN, '',
             '| file | asset | stddev | uniform share | median | flag |',
             '| --- | --- | --- | --- | --- | --- |']
    for r, m, note in sorted(flagged, key=lambda x: (x[1] or {'stddev': 0})['stddev']):
        if m is None:
            lines.append('| %s | %s | - | - | - | %s |' % (r['file'], r['assetName'], note))
        else:
            lines.append('| %s | %s | %.1f | %.0f%% | %d | %s |' % (r['file'], r['assetName'], m['stddev'], m['uniform'] * 100, m['median'], note))
    if not flagged:
        lines.append('')
        lines.append('Nothing was flagged in this run: every exported picture carries visible variation.')
    lines += ['', 'Totals: %d records, %d flagged.' % (len(rows), len(flagged)), '']
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    open(REPORT, 'w', encoding='utf-8').write('\n'.join(lines))
    print('[image-sanity] %d records, %d flagged' % (len(rows), len(flagged)))
    for r, m, note in flagged:
        print('   ' + r['file'] + ' :: ' + note)
    return 0


if __name__ == '__main__':
    sys.exit(main())
